// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimplyBooks;

#nullable disable

namespace SimplyBooksBE.Migrations
{
    [DbContext(typeof(SimplyBooksDbContext))]
    partial class SimplyBooksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimplyBooks.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "charlotte.perkins@example.com",
                            Favorite = true,
                            FirstName = "Charlotte",
                            Image = "charlotte.jpg",
                            LastName = "Perkins Gilman",
                            Uid = "UID001"
                        },
                        new
                        {
                            Id = 2,
                            Email = "daphne.du.maurier@example.com",
                            Favorite = true,
                            FirstName = "Daphne",
                            Image = "dumarier.jpg",
                            LastName = "du Maurier",
                            Uid = "UID002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "jacqueline.harpman@example.com",
                            Favorite = false,
                            FirstName = "Jacqueline",
                            Image = "harpman.jpg",
                            LastName = "Harpman",
                            Uid = "UID003"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ling.ling.huang@example.com",
                            Favorite = false,
                            FirstName = "Ling Ling",
                            Image = "huang.jpg",
                            LastName = "Huang",
                            Uid = "UID004"
                        },
                        new
                        {
                            Id = 5,
                            Email = "nk.jemisin@example.com",
                            Favorite = true,
                            FirstName = "N.K.",
                            Image = "jemisin.jpg",
                            LastName = "Jemisin",
                            Uid = "UID005"
                        });
                });

            modelBuilder.Entity("SimplyBooks.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<bool>("Sale")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "The Yellow Wallpaper by Charlotte Perkins Gilman tells the story of a woman suffering from postpartum depression, who becomes obsessed with the wallpaper in her confinement, revealing the effects of isolation and gender roles.",
                            Image = "yellowwallpaper.jpg",
                            Price = 12.99m,
                            Sale = true,
                            Title = "The Yellow Wallpaper",
                            Uid = "BID001"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Description = "Herland by Charlotte Perkins Gilman is a utopian novel about an all-female society, where women live in harmony, without men",
                            Image = "herland.jpg",
                            Price = 10.99m,
                            Sale = false,
                            Title = "Herland",
                            Uid = "BID002"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Description = "Rebecca by Daphne Du Maurier is a Gothic novel about a young woman who marries a wealthy widower, only to find herself overshadowed by the memory of his first wife, Rebecca. As she uncovers dark secrets about Rebecca's life and death, the narrator struggles with jealousy, mystery, and her own sense of identity.",
                            Image = "rebecca.jpg",
                            Price = 9.99m,
                            Sale = false,
                            Title = "Rebecca",
                            Uid = "BID003"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Description = "My Cousin Rachel by Daphne Du Maurier is a suspenseful novel about a young man who becomes suspicious of his cousin Rachel after his guardian's mysterious death, while grappling with his growing attraction to her.",
                            Image = "rachel.jpg",
                            Price = 12.99m,
                            Sale = true,
                            Title = "My Cousin Rachel",
                            Uid = "BID004"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Description = "I Who Have Never Known Men by Jacqueline Harpman follows a woman who has spent her life in isolation in an underground bunker. When she is suddenly freed, she discovers a world she never knew, struggling to understand human relationships, gender, and identity in a society she was cut off from.",
                            Image = "never_known_men.jpg",
                            Price = 8.99m,
                            Sale = false,
                            Title = "I Who Have Never Known Men",
                            Uid = "BID005"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Description = "Orlanda by Jacqueline Harpman tells the story of a woman who mysteriously transforms into a man and experiences life from both genders' perspectives. The novel explores themes of identity, gender, and the fluidity of self through her journey across time and societal roles.",
                            Image = "orlanda.jpg",
                            Price = 11.99m,
                            Sale = true,
                            Title = "Orlanda",
                            Uid = "BID006"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            Description = "Natural Beauty by Ling Ling Huang is a novel that follows a Chinese-American woman navigating the complexities of beauty standards, cultural identity, and self-acceptance.",
                            Image = "beauty.jpg",
                            Price = 14.99m,
                            Sale = false,
                            Title = "Natural Beauty",
                            Uid = "BID007"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            Description = "Immaculate Conception by Ling Ling Huang is a novel about a young woman grappling with her sense of identity, exploring themes of family, faith, and cultural expectations. As she navigates personal challenges, she confronts the complexities of her heritage and the search for meaning in her life.",
                            Image = "conception.jpg",
                            Price = 15.99m,
                            Sale = true,
                            Title = "Immaculate Conception",
                            Uid = "BID008"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            Description = "The Fifth Season by N.K. Jemisin is a science fiction novel set in a world plagued by constant seismic activity. The story follows three women with the power to control earth movements as they navigate a society on the brink of collapse, exploring themes of survival, power, and the impact of oppression.",
                            Image = "fifth_season.jpg",
                            Price = 17.99m,
                            Sale = true,
                            Title = "The Fifth Season",
                            Uid = "BID009"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            Description = "The City We Became by N.K. Jemisin is a fantasy novel where New York City’s boroughs come to life as human avatars. As a mysterious force threatens the city, these avatars must unite to protect their home. The novel explores themes of identity, power, and the complexities of urban life.",
                            Image = "city_we_became.jpg",
                            Price = 12.49m,
                            Sale = false,
                            Title = "The City We Became",
                            Uid = "BID010"
                        });
                });

            modelBuilder.Entity("SimplyBooks.Models.Book", b =>
                {
                    b.HasOne("SimplyBooks.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SimplyBooks.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
